155 fix
energicryptocurrency/gen2-energi pull request #182
Opened 2017-12-29 10:09 UTC by levongh

2017-12-30 09:37 UTC, levongh commented
![](https://github.trello.services/images/mini-trello-icon.png) [mixhash in block RPC headers](https://trello.com/c/5KerQX6o/99-mixhash-in-block-rpc-headers)

2018-01-04 19:52 UTC, RyanLucchese requested changes

2018-01-04 19:52 UTC, RyanLucchese commented on src/rpc/blockchain.cpp
> +    result.push_back(Pair("hashmix", pnext->hashMix.GetHex()));
This would return the mixhash for the next block in the blockchain, not the current block which is not the right thing to do. Instead we should add the mixhash for the current block. Further, it segmentation faults if you ask for the latest block (pnext will be NULL)

2018-01-04 19:52 UTC, RyanLucchese commented on src/rpc/blockchain.cpp
> +    result.push_back(Pair("hashmix", pnext->hashMix.GetHex()));
This would return the mixhash for the next block in the blockchain, not the current block which is not the right thing to do. Instead we should add the mixhash for the current block. Further, it segmentation faults if you ask for the latest block (pnext will be NULL)

2018-01-05 04:55 UTC, closed without merging

2018-01-05 08:30 UTC, levongh commented
![](https://github.trello.services/images/mini-trello-icon.png) [mixhash in block RPC headers](https://trello.com/c/5KerQX6o/99-mixhash-in-block-rpc-headers)