154 fix
energicryptocurrency/gen2-energi pull request #183
Opened 2017-12-30 09:35 UTC by levongh

2017-12-30 09:37 UTC, levongh commented
![](https://github.trello.services/images/mini-trello-icon.png) [RPC calls for egihash info](https://trello.com/c/cz4XelgI/98-rpc-calls-for-egihash-info)

2018-01-04 20:35 UTC, RyanLucchese requested changes

2018-01-04 20:35 UTC, RyanLucchese commented on src/crypto/egihash.h
> +
The functions specified here are not necessary - egihash already has the appropriate API's needed to return the requested data without requiring a DAG to be loaded. Instead please use the following functions:

* `egihash::get_seedhash()`
* `egihash::cache_t::get_cache_size()`
* `egihash::dag_t::get_full_size()`

To map the parameters you can convert an epoch into a block number or vice versa with the following formula:
` epoch = block_number * egihash::constants::EPOCH_LENGTH`
  
So all changes for this PR should be in Energi Core only, egihash modification should not be required.

2018-01-05 04:56 UTC, closed without merging

2018-01-06 13:31 UTC, levongh commented
Jenkins test this please