Fixed 154 issue
energicryptocurrency/gen2-energi pull request #189
Opened 2018-01-05 08:14 UTC by levongh

RPC calls for egihash info

2018-01-05 08:31 UTC, levongh commented
![](https://github.trello.services/images/mini-trello-icon.png) [RPC calls for egihash info](https://trello.com/c/cz4XelgI/98-rpc-calls-for-egihash-info)

2018-01-05 22:43 UTC, RyanLucchese requested changes

2018-01-05 22:43 UTC, RyanLucchese commented on src/rpc/server.cpp
> +    { "egihash",            "getcache",               &getdag,                 true  },
Looks like there is a typo in the function ptr address here, should be &getcache

2018-01-05 22:43 UTC, RyanLucchese commented on src/rpc/rpcegihash.cpp
> +        epoch = std::stoi(params[0].get_str());
for `getdag` and `getcache` can we have the epoch parameter default to the current epoch if not specified, as in `getseedhash` `getdagsize` and `getcachesize`

2018-01-05 22:43 UTC, RyanLucchese commented on src/rpc/rpcegihash.cpp
> +    return uint256S(get_seedhash(epoch * constants::EPOCH_LENGTH)).GetHex();
Apologies, the documentation for egihash::get_seedhash() was unclear and the API was difficult to use. As implemented this returns seedhash values of all 0 because `get_seedhash()` returns a `std::string` containing binary hash data, and `uint256S()` expects a hex encoded hash. I have updated this in egihash so that there is a new function `egihash::cache_t::get_seedhash()` which returns `h256_t`. So the `get_seedhash()` calls will need to be replaced with `egihash::cache_t::get_seedhash(blocknum).to_hex()`. Please merge the latest develop branch and update to the new seedhash function.

2018-01-06 13:34 UTC, levongh commented
Jenkins test this please

2018-01-11 12:04 UTC, levongh commented
Jenkins test this please

2018-01-11 17:01 UTC, levongh commented
Jenkins test this please

2018-01-12 13:16 UTC, levongh commented
Jenkins test this please

2018-02-05 22:45 UTC, RyanLucchese approved these changes

2018-02-05 22:45 UTC, merged

2018-02-05 22:45 UTC, RyanLucchese commented
Fixes #154