Added handling of dag low memory generation
energicryptocurrency/gen2-energi pull request #234
Opened 2018-02-20 13:59 UTC by sedrakGR

Added generate and save functionality to immediately save the generated dag
    Adjusted the logic of loading/updating dag to use low memory dag generation when a dag is already loaded

2018-02-20 14:00 UTC, sedrakGR commented
![](https://github.trello.services/images/mini-trello-icon.png) [egihash: Low memory generate&save DAG function](https://trello.com/c/Dma6tyCl/45-egihash-low-memory-generatesave-dag-function)

2018-03-15 21:38 UTC, RyanLucchese requested changes

2018-03-15 21:38 UTC, RyanLucchese commented on src/crypto/egihash.h
> +
These two extra members are not necessary and break the API pattern. If necessary to add new members they should be added to the impl_t subclass

2018-03-15 21:38 UTC, RyanLucchese commented on src/crypto/egihash.h
Instead of keeping "empty" dag_t classes around which can be loaded, let's use the dag_t() constructors for loading. Since this happens rarely the extra shared_ptr increment should be no big deal.

2018-03-15 21:38 UTC, RyanLucchese commented on src/crypto/egihash.h
> +
`generateAndSave()` should be static - so it can't modify any state of this object and the usage is more clear. Then it becomes unnecessary for a `dag_t` to distinguish whether it is loaded or unloaded, the low memory and path parameters become unnecessary. A `dag_t` instance should always be loaded at construction, I think this would be a much more clear usage pattern in line with typical RAII principles.

2018-03-15 21:38 UTC, RyanLucchese commented on src/dag_singleton.cpp
>      {
This section has some merge conflicts with the latest `develop` branch, please update & resolve conflicts

2018-03-15 21:38 UTC, RyanLucchese commented on src/validation.cpp
>      {
For this case of DAG loading the low memory function is not necessary - we are going to end up with a single dag in memory either way since we are initializing. Really the main point to be concerned is `ConnectTip()`

2018-03-15 21:38 UTC, RyanLucchese commented on src/validation.cpp
>      auto const & active_dag = ActiveDAG();
Since the a dag may take 30 minutes to generate, let's start the `generateAndSave()` 30 blocks early here to ensure a DAG can be loaded quickly when it's time to switch.

2018-03-26 12:01 UTC, closed without merging